### ISSUE TITLE
Is Cookie-Domain-Help a typo?

### ISSUE THREAD

**Issue by littlegolden** [extiverse/premium-translations#1]
cookie_domain_help: 
```
Only necessary it's different than Flarum domain
```

of it shoud be
```
Only necessary if it's different than Flarum domain
```

https://github.com/extiverse/premium-translations/blob/bc66049ff0345ab4bc1aba3a6c89ce5e93bff511/kilowhat-wordpress.yml#L18

**Comment by luceos** [comment]
@clarkwinkelmann please review.

@Littlegolden this has totally been ignored, I am terribly sorry.

**Comment by clarkwinkelmann** [comment]
Thanks for the report. I have now updated the text with "Only necessary if different from Flarum domain" in English. It will ship in the next release.
